.TH "C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI Directory Reference" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCOMMON_MACROS\&.h\fP"
.br
.ti -1c
.RI "file \fBDIO\&.c\fP"
.br
.ti -1c
.RI "file \fBDIO\&.h\fP"
.br
.ti -1c
.RI "file \fBDoor_locker_project\&.c\fP"
.br
.RI "\fIMain Program of HMI ECU\&. \fP"
.ti -1c
.RI "file \fBHMI_SYS\&.c\fP"
.br
.RI "\fIModule for HMI ECU used to initialize HMI system,interface with user to setup password and receive menu option and send it to CNTRL ECU\&. \fP"
.ti -1c
.RI "file \fBHMI_SYS\&.h\fP"
.br
.RI "\fIModule for HMI ECU used to initialize HMI system,interface with user to setup password and receive menu option and send it to CNTRL ECU\&. \fP"
.ti -1c
.RI "file \fBKeypad\&.c\fP"
.br
.RI "\fIKeypad Module for door locker program\&. \fP"
.ti -1c
.RI "file \fBKeypad\&.h\fP"
.br
.RI "\fIKeypad Module for door locker program\&. \fP"
.ti -1c
.RI "file \fBLCD\&.c\fP"
.br
.RI "\fILCD Module for general use\&. \fP"
.ti -1c
.RI "file \fBLCD\&.h\fP"
.br
.RI "\fILCD Module for general use\&. \fP"
.ti -1c
.RI "file \fBSTD_TYPE\&.h\fP"
.br
.ti -1c
.RI "file \fBUART\&.c\fP"
.br
.ti -1c
.RI "file \fBUART\&.h\fP"
.br
.in -1c
