.TH "C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_CNTRL/Door_locker_CNTRL_ECU Directory Reference" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_CNTRL/Door_locker_CNTRL_ECU Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCNTRL_SYS\&.c\fP"
.br
.RI "\fIModule for CNTRL ECU used to initialize cntrol system, setup password and execute the received menu option\&. \fP"
.ti -1c
.RI "file \fBCNTRL_SYS\&.h\fP"
.br
.RI "\fIModule for CNTRL ECU used to initialize cntrol system, setup password and execute the received menu option\&. \fP"
.ti -1c
.RI "file \fBCOMMON_MACROS\&.h\fP"
.br
.ti -1c
.RI "file \fBDIO\&.c\fP"
.br
.ti -1c
.RI "file \fBDIO\&.h\fP"
.br
.ti -1c
.RI "file \fBDoor_locker_CNTRL_ECU\&.c\fP"
.br
.RI "\fIMain Program of CNTRL ECU\&. \fP"
.ti -1c
.RI "file \fBEEPROM\&.c\fP"
.br
.RI "\fIEEPROM module to write and read from EEPROM using I2C\&. \fP"
.ti -1c
.RI "file \fBEEPROM\&.h\fP"
.br
.RI "\fIEEPROM module to write and read from EEPROM using I2C\&. \fP"
.ti -1c
.RI "file \fBI2C\&.c\fP"
.br
.RI "\fII2C communication module\&. \fP"
.ti -1c
.RI "file \fBI2C\&.h\fP"
.br
.RI "\fII2C communication module\&. \fP"
.ti -1c
.RI "file \fBmotor\&.c\fP"
.br
.RI "\fImotor Module contain functions to control all motors in the system \fP"
.ti -1c
.RI "file \fBmotor\&.h\fP"
.br
.RI "\fImotor Module contain functions to control all motors in the system \fP"
.ti -1c
.RI "file \fBSTD_TYPE\&.h\fP"
.br
.ti -1c
.RI "file \fBTimer\&.c\fP"
.br
.RI "\fITimer Module for Timers initializations to work in PWM mode &\&. \fP"
.ti -1c
.RI "file \fBTimer\&.h\fP"
.br
.RI "\fITimer Module for Timers initializations to work in PWM mode &\&. \fP"
.ti -1c
.RI "file \fBUART\&.c\fP"
.br
.ti -1c
.RI "file \fBUART\&.h\fP"
.br
.in -1c
