.TH "C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI/HMI_SYS.h" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI/HMI_SYS.h \- 
.PP
Module for HMI ECU used to initialize HMI system,interface with user to setup password and receive menu option and send it to CNTRL ECU\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Keypad\&.h'\fP
.br
\fC#include 'LCD\&.h'\fP
.br
\fC#include 'UART\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpasswords\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpasswords\fP \fBpass\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSYS_HMI_Init\fP (void)"
.br
.ti -1c
.RI "uint8 \fBSYS_HMI_setup_password\fP (void)"
.br
.ti -1c
.RI "void \fBSYS_check_Password_EEPROM\fP (void)"
.br
.ti -1c
.RI "void \fBSYS_HMI_menu_option_send\fP (uint8 menu_option)"
.br
.ti -1c
.RI "uint8 \fBSYS_HMI_get_menu_option\fP (void)"
.br
.ti -1c
.RI "void \fBSYS_HMI_resend_menu_option\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module for HMI ECU used to initialize HMI system,interface with user to setup password and receive menu option and send it to CNTRL ECU\&. 


.PP
\fBDate:\fP
.RS 4
11/19/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
a7med 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition in file \fBHMI_SYS\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void SYS_check_Password_EEPROM (void)"
Description: Function is used to get the status of password form CNTRL unit using UART 
.PP
Definition at line 221 of file HMI_SYS\&.c\&.
.SS "uint8 SYS_HMI_get_menu_option (void)"
Description: Function is used to get menu option from user 
.PP
Definition at line 368 of file HMI_SYS\&.c\&.
.SS "void SYS_HMI_Init (void)"
Description: Function is used to Initialize HMI system 
.PP
Definition at line 16 of file HMI_SYS\&.c\&.
.SS "void SYS_HMI_menu_option_send (uint8menu_option)"
Description: Function is used to send menu option to CNTRL unit 
.PP
Definition at line 257 of file HMI_SYS\&.c\&.
.SS "void SYS_HMI_resend_menu_option (void)"
Description: Function is used to resend the menu option 
.PP
Definition at line 390 of file HMI_SYS\&.c\&.
.SS "uint8 SYS_HMI_setup_password (void)"
Description: Function is used to Initialize HMI system and setup password if not set and return the value of menu option 
.PP
Definition at line 26 of file HMI_SYS\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Door_locker_system from the source code\&.
