.TH "C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_CNTRL/Door_locker_CNTRL_ECU/I2C.h" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_CNTRL/Door_locker_CNTRL_ECU/I2C.h \- 
.PP
I2C communication module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'DIO\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTWI_Init\fP (void)"
.br
.ti -1c
.RI "void \fBTWI_start\fP (void)"
.br
.ti -1c
.RI "void \fBTWI_stop\fP (void)"
.br
.ti -1c
.RI "void \fBTWI_write\fP (uint8 data)"
.br
.ti -1c
.RI "uint8 \fBTWI_read_ack\fP (void)"
.br
.ti -1c
.RI "uint8 \fBTWI_read_Nack\fP (void)"
.br
.ti -1c
.RI "uint8 \fBTWI_get_status\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C communication module\&. 


.PP
\fBDate:\fP
.RS 4
11/15/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
a7med 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBI2C\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "uint8 TWI_get_status (void)"
Description: Function is used to get status of TWI 
.PP
Definition at line 73 of file I2C\&.c\&.
.SS "void TWI_Init (void)"
Description: Function is used to Initialize I2C module to be ready for using 
.PP
Definition at line 14 of file I2C\&.c\&.
.SS "uint8 TWI_read_ack (void)"
Description: Function is used to receive data and send acknowledge signal 
.PP
Definition at line 53 of file I2C\&.c\&.
.SS "uint8 TWI_read_Nack (void)"
Description: Function is used to receive data without sending an acknowledgment 
.PP
Definition at line 63 of file I2C\&.c\&.
.SS "void TWI_start (void)"
Description: Function is used to Send start signal 
.PP
Definition at line 26 of file I2C\&.c\&.
.SS "void TWI_stop (void)"
Description: Function is used to Send stop signal 
.PP
Definition at line 35 of file I2C\&.c\&.
.SS "void TWI_write (uint8data)"
Description: Function is used to write data or address on SDA line 
.PP
Definition at line 43 of file I2C\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Door_locker_system from the source code\&.
