.TH "C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI/Keypad.c" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/a7med/Desktop/Embbeded Project/Project code/Door_locker_project/Door_locker_project_HMI/Keypad.c \- 
.PP
Keypad Module for door locker program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Keypad\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8 \fBKeypad_get_pressed_key\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8 \fBkey_table\fP [4][4] ={ {'/','9','8','7'},{'x','6','5','4'},{'-','3','2','1'},{'+','=','0','c'} }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keypad Module for door locker program\&. 


.PP
\fBDate:\fP
.RS 4
11/1/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
a7med 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition in file \fBKeypad\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "uint8 Keypad_get_pressed_key (void)"
Description: Function used to get the keypad pressed key 
.PP
Definition at line 19 of file Keypad\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Door_locker_system from the source code\&.
