.TH "passwords" 3 "Sat Nov 22 2014" "Door_locker_system" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passwords \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CNTRL_SYS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8 \fBfrist_time_flag\fP"
.br
.ti -1c
.RI "uint8 \fBpassword_saved_flag\fP"
.br
.ti -1c
.RI "uint8 \fBpassword_correctly_enterd_flag\fP"
.br
.ti -1c
.RI "uint8 \fBpasswrd\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Structure to carry password and its status it contain
.IP "1." 4
the frist_time_flag --> the frist time to use system (0) or not (1)
.IP "2." 4
the password_saved_flag --> password saved (1) or (0)
.IP "3." 4
the password_correctly_entered_flag --> password match with password on EEPROM (1) or mismatch(0)
.IP "4." 4
the password 
.PP

.PP
Definition at line 25 of file CNTRL_SYS\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Door_locker_system from the source code\&.
